


export const Team3 = [
    { id: 1, name: 'Barcelona',    image: 'assets/logos/barcelona.png', location: 'Barcelona, Spain', stadium:    'Camp Nou',
    capacity:    99354, manager: 'Quique Setien', captain: 'Lionel Messi', lat: 41.38087, lng: 2.122802 },
    { id: 2, name: 'Real Madrid',    image: 'assets/logos/real-madrid.png', location:    'Madrid, Spain', stadium: 'Santiago Bernabeu Stadium',
    capacity: 81044, manager: 'Zinedine Zidane', captain: 'Sergio Ramos', lat: 40.45306, lng: 3.68835 },
    { id: 3, name: 'Atletico Madrid',    image: 'assets/logos/atletico.png',    location:    'Madrid, Spain', stadium:    'Metropolitano Stadium',
    capacity: 68456, manager: 'Diego Simeone', captain: 'Jorge Resurreccion Merdio (Koke)', lat: 40.2610, lng: 3.3558 },
    { id: 4, name: 'Sevilla F.C',    image: 'assets/logos/sevilla.png', location: 'Seville, Andalusia', stadium:    'Estadio Rafa Bolance',
    capacity: 42714, manager: 'Julen Lopetegui', captain: 'Jesus Navas', lat: 37.2367, lng: 5.98356 },
    { id: 5, name: 'S.D Eibar',    image: 'assets/logos/eibar.png',    location:    'Eibar, Spain', stadium:    'Estadio de Ipurua',
    capacity: 7083, manager: 'Jose Luis Mendillibar', captain: 'Ivan Ramis', lat: 43.105414, lng: 2.283289  },
    { id: 6, name: 'Levante',    image: 'assets/logos/levante.png',    location:    'Valencia, Spain', stadium:    'Estadio Ciutat de Valencia',
    capacity: 25352, manager: 'Paco Lopez', captain: 'Jose Luis Morales', lat: 39.2941, lng: -0.2151 },
    { id: 7, name: 'Real Betis',    image: 'assets/logos/real-betis.png', location: 'Sevilla, Spain', stadium: 'EStadio benito Villamarin',
    capacity: 51700, manager: 'Rubi', captain: 'Joaquin', lat: 37.2123, lng: -5.5853 },
    { id: 8, name: 'Valencia C.F',    image: 'assets/logos/valencia.png',    location:    'Valencia, Spain', stadium: 'Estadio de Mestalla',
    capacity: 55000, manager: 'Albert Celades', captain: 'Dani Parejo', lat: 39.2828, lng: 0.2130 },
    { id: 9, name: 'Real Sociedad',    image: 'assets/logos/real-sociedad.png', location: 'San Sebastian', stadium: 'Estadio Anoeta',
    capacity:    32000, manager: 'Imanol Alguacil', captain: 'Asier Illarramendi', lat: 43.18496, lng: 1.582502 },
    { id: 10, name: 'Getafe C.F',    image: 'assets/logos/getafe.png', location: 'Getafe, Spain', stadium: 'Coliseum Alfonso Perez',
    capacity: 17500, manager: 'Jose Bordalas', captain: 'Gorge Molina', lat: 40.1932, lng: 3.4253 },
    { id: 11, name:    'Athletic Bilbao',    image: 'assets/logos/atletic-bilbao.png', location: 'Bilbao, Spain',
    stadium: 'Estadio San Mames', capacity: 53000, manager: 'Gaizka Garitano', captain: 'Iker Muniain',
    lat: 43.1551, lng: 2.5701 },
    { id: 12, name:    'Espanyol de Barcelona',    image: 'assets/logos/espanyol.png', location: 'Barcelona', stadium: 'RCDE Stadium',
    capacity: 40500, manager: 'Abelardo', captain: 'Javi Lopez', lat: 41.20523, lng: 2.4324 },
    { id: 13, name:    'Celta de Vigo',    image: 'assets/logos/celtavigo.png', location: 'Vigo, Spain', stadium: 'Estadio Municipal de Balaidos',
    capacity: 31800, manager: 'Oscar Garcia', captain: 'Hugo Mallo', lat: 42.211842, lng: 8.739711 },
    { id: 14, name:    'C.D Leganes',    image: 'assets/logos/leganes.png', location: 'Leganes, Madrid Spain', stadium:    'Estadio Municipal de Butarque',
    capacity: 8138, manager: 'Javier Aguirre', captain: 'Unai Bustinza', lat:40.4524, lng: 3.46788 },
    { id: 15, name:    'Villarreal C.F',    image: 'assets/logos/villareal.png', location: 'Villareal, Spain', stadium: 'Estadio El Madrigal',
    capacity: 25000, manager: 'Javier Calleja', captain: 'Bruno Soriano', lat: 42.78654, lng:  3.98654 },
    { id: 16, name:    'Real Valladolid',    image: 'assets/logos/valladolid.png', location: 'Valladolid', stadium: 'Jose Zorrilla Valladolid',
    capacity: 27846, manager: 'Sergio Gonzalez', captain: 'Javi Moyano', lat: 41.3840, lng: 4.4540 },
    { id: 17, name:    'C.A Osasuna',    image: 'assets/logos/osasuna.png', location: 'Pamplona, Spain',
    stadium:    'El Sadar', capacity: 18375, manager: 'Jagoba Arrasate', captain: 'Oier Sanjurjo Mate', lat: 42.4748, lng: 1.3813 },
    { id: 18, name:    'Deportivo Alaves',    image: 'assets/logos/alaves.png', location: 'Vitoria Gasteiz', stadium: 'EStadio de Mendizorrotza',
    capacity: 20400, manager: 'Asier Garitano', captain: 'Manu Garcia', lat: 42.501360, lng: 2.411696 },
    { id: 19, name:    'Granada C.F',    image: 'assets/logos/granada.png', location: 'Andalusia, Spain', stadium: 'Estadio Nuevo Los Carmenes',
    capacity: 19336, manager: 'Diego Martinez', captain: 'Victor Diaz', lat: 37.91068, lng: 3.354465 },
    { id: 20, name:    'Rayo Vallecano',    image: 'assets/logos/vallecano.png', location: 'Madrid, Spain',
    stadium: 'Campo de Futbol de Vallecas', capacity: 14708, manager: 'Paco Jemez', captain: 'Alberto Garcia', lat: 40.2331, lng: 3.393226 },
    { id: 21, name:    'R.C.D Mallorca',    image: 'assets/logos/mallorca.png', location: 'Palma, Balearic Islands',
    stadium: 'Iberostar Stadium', capacity: 23142, manager: 'Vicente Moreno', captain: 'Xisco Campos', lat: 39.3524, lng: 2.3748 }
    
  ];