


export const Team2 = [
    { id: 1, name: 'Juventus',    image: 'assets/logos/juventus.png', location: 'Turin Italy', stadium:    'Allianz Stadium',
    capacity:    41507, manager: 'Maurizio Sarri', captain: 'Giorgio Chiellini', lat: 45.1096, lng: 7.6413 },
    { id: 2, name: 'Inter Milan',    image: 'assets/logos/inter-milan.png', location:    'Milan, lombardy', stadium: 'San Siro',
    capacity: 80018, manager: 'Antonio Conte', captain: 'Samir Handanovic', lat: 45.478489, lng: 9.122150 },
    { id: 3, name: 'A.C Milan',    image: 'assets/logos/ac-milan.png',    location:    'Milan, Lombardy', stadium:    'San Siro',
    capacity: 80018, manager: 'Stenfano Pioli', captain: 'Alessio Romagnoli', lat: 45.4586, lng: 9.1819 },
    { id: 4, name: 'S.S.C Napoli',    image: 'assets/logos/napoli.png', location: 'Naples, Campania', stadium:    'San Paolo Stadium',
    capacity: 54726, manager: 'Gennaro Gattuso', captain: 'Lorenzo Insigne', lat: 40.8279, lng: 14.1931 },
    { id: 5, name: 'A.S. Roma',    image: 'assets/logos/roma.png',    location:    'Rome, Italy', stadium:    'Stadio Olimpico',
    capacity: 70634, manager: 'Edin Dzeko', captain: 'Ben Mee', lat: 41.9341, lng: 12.4547 },
    { id: 6, name: 'SS Lazio',    image: 'assets/logos/lazio.png',    location:    'Rome, Italy', stadium:    'Stadio Olimpico',
    capacity: 70634, manager: 'Simone Inzaghi', captain: 'Senad Lulic', lat: 41.9341, lng: 12.4547 },
    { id: 7, name: 'Atalanta B.C',    image: 'assets/logos/atalanta.png', location: 'Bergamo, Lombardy', stadium: 'Gewiss Stadium',
    capacity: 21300, manager: 'Gian Piero Gaspeini', captain: 'Papu Gomez', lat: 45.4232, lng: 9.4051 },
    { id: 8, name: 'ACF Fiorentina',    image: 'assets/logos/fiorentina.png',    location:    'Florence, Tuscany', stadium: 'Stadio Artemio franchi',
    capacity: 43147, manager: 'Gluseppe Iachini', captain: 'German Pezzella', lat: 43.7808, lng: 11.2826 },
    { id: 9, name: 'U.S Leece',    image: 'assets/logos/leece.png', location: 'Leece, Apulia', stadium: 'Stadio Via del Mare',
    capacity:    32312, manager: 'Fabio Liverani', captain: 'Marco Mancosu', lat: 40.3651, lng: 18.2090 },
    { id: 10, name: 'Brescia Calcio',    image: 'assets/logos/brescia.png', location: 'Brescia Lombardy', stadium: 'Stadio Mario Rigamonti',
    capacity: 19500, manager: 'Diego Lopez', captain: 'Daniele Gastaldello', lat: 45.5707, lng: 10.2371 },
    { id: 11, name:    'S.P.A.L',    image: 'assets/logos/spal.png', location: 'Ferrara, Italy',
    stadium: 'Stadio Paolo Mazza', capacity: 16134, manager: 'Luigi Di Biagio', captain: 'Sergio Floccari',
    lat: 44.8402, lng: 11.6080 },
    { id: 12, name:    'Genoa C.F.C',    image: 'assets/logos/genoa.png', location: 'Genoa, Italy', stadium: 'Stadio Luigi Ferraris',
    capacity: 36599, manager: 'Davide Nicola', captain: 'Domenico Criscito', lat: 44.243548, lng: 8.57523 },
    { id: 13, name:    'U.C Sampdoria',    image: 'assets/logos/sampdoria.png', location: 'Genoa, Liguria', stadium: 'Stadio Luigi Ferraris',
    capacity: 36599, manager: 'Claudio Ranieri', captain: 'Fabio Quagliarella', lat: 44.243548, lng: 8.57523 },
    { id: 14, name:    'Torino F.C',    image: 'assets/logos/torino.png', location: 'Turin, Piedmont', stadium:    'Stadio Olimpico Grande Torino', 
    capacity: 27958, manager: 'Moreno Longo', captain: 'Andrea Belloti', lat: 45.23030, lng: 7.39005 },
    { id: 15, name:    'Cagliari Calcio',    image: 'assets/logos/cagliari.png', location: 'Cagliari Sardinia', stadium: 'Sardegna Arena',
    capacity: 16223, manager: 'Ronaldo Maran', captain: 'Luca Ceppitelli', lat: 39.1998, lng:  9.1375 }, 
    { id: 16, name:    'Bologna F.C',    image: 'assets/logos/bologna.png', location: 'Bologna, Emilia-Romagna', stadium: 'Stadio Renato DallAra',
    capacity: 38279, manager: 'Sinisa Mihajlovic', captain: 'Andrea Poli', lat: 44.4922, lng: 11.3099 },
    { id: 17, name:    'Udinese Calcio',    image: 'assets/logos/udinese.png', location: 'udine, Fruili-Venezia Giulia',
    stadium:    'Stadio Fruili', capacity: 25144, manager: 'Luca Gotti', captain: 'Kevin Lasagna', lat: 46.081603, lng: 13.200136 },
    { id: 18, name:    'Palma Calcio 1913',    image: 'assets/logos/palma.png', location: 'Palma, Emilia-Romagna', stadium: 'Stadio Ennio Tardini',
    capacity: 22359, manager: 'Roberto DAversa', captain: 'Bruno Alves', lat: 44.47417, lng: 10.20184 },
    { id: 19, name:    'Hellas Verona F.C',    image: 'assets/logos/hellas.png', location: 'Verona Veneto', stadium: 'Stadio MarcAntonio Bentegodi',
    capacity: 39371, manager: 'Ivan Juric', captain: 'Giampaolo Pazzini', lat: 45.26384, lng: 10.59276 },
    { id: 20, name:    'U.S Sassuolo',    image: 'assets/logos/sassuolo.png', location: 'Sassuolo, Emilia-Romagna',
    stadium: 'Mapei Stadium-Citta del Tricolore', capacity: 23717, manager: 'Roberto De Zerbi', captain: 'Francesco Magnanelli', lat: 44.47417, lng: 10.20184 },
  { id: 21, name:    'Calcio Catania',    image: 'assets/logos/catania.png', location: 'catania Sicily',
  stadium: 'Stadio Angelo Massimino', capacity: 23226, manager: 'Cristiano Lucarelli', captain: 'Marco Biagianti', lat: 37.5162, lng: 15.0722 },
  { id: 22, name:    'Empoli F.C',    image: 'assets/logos/empoli.png', location: 'Empoli Tuscani',
  stadium: 'Stadio Carlco Castellani', capacity: 16284, manager: 'Pasquale Marino ', captain: 'Domenico Maietta', lat: 43.7265, lng: 10.9548 },
  { id: 23, name:    'Ascoli Calcio',    image: 'assets/logos/ascoli.png', location: 'Ascoli Piceno Marche',
  stadium: 'Stadio Cino e Lillo Del Duca', capacity: 12461, manager: 'Roberto Stellone', captain: 'Bright Addae', lat: 42.8611, lng: 13.5939 },
  { id: 24, name:    'A.S Livorno Calcio',    image: 'assets/logos/livorno.png', location: 'Ardenza Livorno',
  stadium: 'Stadio Armando Picchi', capacity: 19238, manager: 'Roberto Breda', captain: 'Andrea Luci', lat: 43.33654, lng: 10.19572 },
  { id: 25, name:    'U.S Catanzaro',    image: 'assets/logos/catanzaro.png', location: 'Catanzaro, Calbria',
  stadium: 'Stadio Nicola Ceravolo', capacity: 14650, manager: 'Gaetano Auteri', captain: 'Rocco Mittica', lat: 38.9204, lng: 16.5871 },

];